import "./globals.css";
import Header from "./Component/Header";
import Footer from "./Component/Footer";
import PageWrapper from "./Component/PageWrapper";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          {/* <PageWrapper> */}
            <Header />
            {children}
            <Footer />
          {/* </PageWrapper> */}
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
